name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    permissions:
      # Required to allow actions/checkout to clone the repository onto the runner
      contents: read
      # Required to allow the vitest coverage action to write a comment into the pull request
      pull-requests: write
    # ... rest of the node.js.yml

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      # ... rest of the node.js.yml
      - run: npm run test
      - uses: davelosert/vitest-coverage-report-action@v1
        with:
          vite-config-path: vite.config.ts

      - run: npm run build --if-present

      - name: Run tests with coverage
        run: npx vitest --coverage.enabled true

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
